images
iSchoolProjects/fotodesk_frontend pull request #77
Opened 2022-10-11 08:04 UTC by Borislav466

2022-10-13 11:38 UTC, zlayabekrija requested changes
Please apply requested changes

2022-10-13 11:38 UTC, zlayabekrija commented on src/api/images.api.ts
> +    return await this.get(`/images${filterQuery ? filterQuery : ''}`, undefined, query);
Why is get method updated, it should remain as is. Same applies for ```getImages``` method. Please apply suggestions and reach out @MateoKusan98 for help.

2022-10-13 11:38 UTC, zlayabekrija commented on src/api/images.api.ts
> +  public async Images(token: string, params?: any): Promise<any> {
Please follow naming pattern for function names.

2022-10-13 11:38 UTC, zlayabekrija commented on src/components/ImagePagination/ImagePagination.tsx
> +      setSelectedQuery(`?${links?.last?.split('?')?.at(-1)}`);
Why does going back brings you to the last page
Please refactor this method to receive  a link need without additional logic.
Reach out @MateoKusan98 or @BaneIT for help.

2022-10-13 11:38 UTC, zlayabekrija commented on src/components/Images/Images.tsx
> +          <datalist id="datalistOptions">
Why do we have hardcoded values???

2022-10-13 13:39 UTC, zlayabekrija requested changes
Please address give comments, and do not hesitate to reach out for help

@lazarevic-00 @BaneIT @MateoKusan98 please have a look.

2022-10-13 13:39 UTC, zlayabekrija commented on src/components/ImagePagination/ImagePagination.tsx
> +  console.log(images?.links);
Please remove console log

2022-10-13 13:39 UTC, zlayabekrija commented on src/components/ImagePagination/ImagePagination.tsx
> +  const nextDisabled = images?.links?.next === undefined;
Why ???
Passing undefined as an argument should be sufficient

2022-10-13 13:39 UTC, zlayabekrija commented on src/components/ImagePagination/ImagePagination.tsx
> +  const prevDisabled = images?.links?.first === undefined;
Same as above

2022-10-13 13:39 UTC, zlayabekrija commented on src/components/PendingImages/PendingImages.tsx
> +        const {data} = await imagesApi.Images(user.token!, {'filter.isApproved': 1});
Nope, pending images should stay as 0

2022-10-18 12:35 UTC, MateoKusan98 requested changes

2022-10-18 12:35 UTC, MateoKusan98 commented on src/components/Images/Images.tsx
> +            <option />
Please remove  options if we got no values

2022-10-18 12:59 UTC, AleksandarGajic01 approved these changes
LGTM!

2022-10-19 12:13 UTC, zlayabekrija requested changes
Please merge main branch in yours

2022-10-19 12:13 UTC, zlayabekrija commented on src/components/Detail/Detail.tsx
> +                {data.map((watermark, key) => {
Nice :+1:

2022-10-19 12:13 UTC, zlayabekrija commented on src/components/Detail/Detail.tsx
> +                {data.map((watermark, key) => {
Why do we have it twice

2022-10-25 14:45 UTC, zlayabekrija approved these changes

2022-10-25 14:45 UTC, merged