added_upload_watermark_option
iSchoolProjects/fotodesk_frontend pull request #79
Opened 2022-10-12 13:30 UTC by Dysfunctional89

2022-10-13 11:42 UTC, zlayabekrija requested changes
Please apply requested changes

2022-10-13 11:42 UTC, zlayabekrija commented on src/components/Watermarks/UploadWatermarks.tsx
> +import React, {CSSProperties, useState} from 'react';
Please reuse Upload step one component as much as possible.

Please reach out to @MateoKusan98  or @BaneIT

2022-10-14 15:03 UTC, lazarevic-00 requested changes
Please apply suggested changes

2022-10-14 15:03 UTC, lazarevic-00 commented on src/components/Upload/Upload.tsx
> +        <button className={`proceed ${toggleProceed}`} type="submit" onClick={() => submit ? handleSubmit() : handleProceed()}>
You should pass only one function if you are trying to create reusable component.

2022-10-14 15:03 UTC, lazarevic-00 commented on src/components/UploadImages/UploadStepOne.tsx
> +    <>
You don't need fragment here, also, API should be already assigned here.

2022-10-14 15:03 UTC, lazarevic-00 commented on src/components/Watermarks/UploadWatermarks.tsx
> +        <>
Same here

2022-10-14 15:03 UTC, lazarevic-00 commented on src/components/Watermarks/Watermarks.tsx
> +      <div className="row">{data && data?.map((watermark) => <Watermark key={watermark.name} {...watermark} user={user} />)}</div>
You dont need here "?" on data if we have data &&

2022-10-17 13:20 UTC, BaneIT commented on src/Pages/AdminPage/AdminPageUploadWatermarks.tsx
> +export default function AdminPageUploadWatermarks(isDefault: any) {
Remove the parameters if you don't use them

2022-10-18 07:45 UTC, zlayabekrija approved these changes
Great work :+1:

2022-10-18 07:45 UTC, merged